#!/bin/bash
# ==========================================
 
# Colors
G='\e[1;32m'
R='\e[1;31m'
C='\e[1;36m'
Y='\e[1;33m'
W='\e[0m'
 
echo -e "${C}[*] DANI HACKER  FB Version 1.0 Checking System Health...${W}"
 
# --- STEP 1: LOCK & REPO FIX ---
killall apt apt-get 2>/dev/null
rm -f /data/data/com.termux/files/usr/var/lib/dpkg/lock*
 
echo "deb https://packages.termux.dev/apt/termux-main stable main" > $PREFIX/etc/apt/sources.list
 
# --- STEP 2: VERSION & MODULE CHECK ---
PY_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null)
 
if [ "$PY_VER" != "3.13" ]; then
    echo -e "${Y}[!] System Upgrade Required. Fixing Termux...${W}"
    export DEBIAN_FRONTEND=noninteractive
    
    apt-get update -y -q --allow-insecure-repositories
    apt-get install -y -q --allow-unauthenticated termux-keyring
    
    echo -e "${Y}[*] Installing Python 3.13...${W}"
    apt-get update -y -q
    apt-get install -y -q -o Dpkg::Options::="--force-confold" python
    
    echo -e "${Y}[*] Installing required modules for Python 3.13...${W}"
    python3 -m pip install requests pycryptodome rich --quiet
    
    echo -e "${G}[✔] System Successfully Upgraded to 3.13 with all modules!${W}"
else
    if ! python3 -c "import requests" &>/dev/null; then
        echo -e "${Y}[!] Modules missing in Python 3.13. Installing now...${W}"
        python3 -m pip install requests pycryptodome rich --quiet
    fi
    echo -e "${G}[✔] System is Healthy.${W}"
fi
 
# --- STEP 3: SMART LAUNCHER ---
# KHAN replace with FIRE
ARCH=$(uname -m)
if [[ "$ARCH" == "aarch64" ]]; then
    chmod +x FIRE && ./FIRE "$@"
elif [[ "$ARCH" == armv* ]] || [[ "$ARCH" == "x86_64" ]] || [[ "$ARCH" == "i686" ]]; then
    chmod +x FIRE && ./FIRE "$@"
else
    echo -e "${R}[!] Fatal Error: Unrecognized Architecture ($ARCH)${W}"
fi
